server:
  port: 8054
#注册中心
eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: "http://localhost:8051/eureka"
spring:
  application:
    name: com-liu-orderservice
  kafka:
    listener:
      poll-timeout: 6000
    producer:
      acks: 0
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      group-id: "com-liu"
      auto-offset-reset: "earliest"
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    bootstrap-servers: "172.31.206.211:9092"
logging:
  level: info

#服务降级时间
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 1000
      circuitBreaker:
        requestVolumeThreshold: 2 #设置一个窗口内的请求数，当在该窗口内(即时间内)请求数达到了该值，则断路器会被打开 默认20
        sleepWindowInMilliseconds: 20000 #设置在断路打开后，拒绝请求到再次尝试请求并决定断路器是否继续打开的时间 默认默认5000毫秒